#!/usr/bin/env python3
"""Portable (source-only) projects: everything needed to rebuild a display project lives in editable assets.

python3 hmi_project.py unpack --portable project.HMI dir      # PNG pictures, JSON pages, text script, binary fonts/animations
python3 hmi_project.py pack dir result.HMI --config project.json

A portable directory needs no original `.HMI`, no `files/` and no manifest, so it can be committed to Git as is:

  project.json              ordered pages / pictures / fonts / animations, per-type attribute layouts, project header
  pages/<key>.json          one lossless, human-editable file per page
  pictures/<key>.png        pictures as PNG (compiled `.i` + `.is` are generated)
  fonts/<key>.zi            compiled fonts (there is no TTF source for them; or use a `ttf` source)
  animations/<key>/NNN.png  animation frames (compiled `.gmov` + `.gmovs` are generated by hmi_anim.py)
  Program.s                 startup script

Ids are never written as numbers: attributes use {"$ref": "picture:KEY"} and code uses ${page:KEY}, ${picture:KEY},
${font:KEY}, ${obj:PAGE/OBJECT}; the position in each list is the id. Inserting, deleting and reordering therefore needs
no renumbering. A page file keeps what the format stores (attribute order and widths via `layouts`, header bytes, table
words, trailers), so rebuilding an unedited project gives byte-identical pages, `Program.s`, fonts and animations.
Pictures are re-encoded from their PNG (Pillow), which is not byte-identical to the editor's compressor; file names and
the order of files inside the container are chosen by this tool.
"""
import hashlib
import json
import re
import shutil
import struct
from pathlib import Path

import hmi_anim as ANIM
import hmi_config as C
import hmi_factory as F
import hmi_image as IMG
import hmi_integrity as I
import hmi_model as M
import hmi_parse as H
import hmi_project as P
import hmi_refs as R

ASSET_KINDS = {'i': 'pictures', 'zi': 'fonts', 'gmov': 'animations'}
TEXT, HEXV = 't', 'h'


def _slug(text, fallback):
    key = re.sub(r'[^A-Za-z0-9_.\-]', '_', text) or fallback
    return key


def _layout_of(obj):
    out = []
    for a in obj.attrs:
        if a.name in M.TEXT_ATTRS:
            out.append([a.name, TEXT])
        elif len(a.value) in (1, 2, 4):
            out.append([a.name, len(a.value)])
        else:
            out.append([a.name, HEXV])
    return out


# ------------------------------------------------------------------ export

class _Symbols:
    """Final-id -> placeholder tables for one exported project (ids are positions in the exported lists)."""

    def __init__(self, page_keys, pic_keys, font_keys, obj_keys, anim_keys=()):
        self.page_keys, self.pic_keys, self.font_keys, self.obj_keys = page_keys, pic_keys, font_keys, obj_keys
        self.anim_keys = anim_keys

    def ref(self, domain, value):
        keys = {'page': self.page_keys, 'pic': self.pic_keys, 'font': self.font_keys, 'anim': self.anim_keys}[domain]
        label = {'pic': 'picture', 'anim': 'animation'}.get(domain, domain)
        return '%s:%s' % (label, keys[value]) if 0 <= value < len(keys) else None

    def placeholder(self, domain, value, comp_page):
        if domain == 'comp':
            if comp_page is None or not 0 <= comp_page < len(self.obj_keys) or not 0 <= value < len(self.obj_keys[comp_page]):
                return None
            return '${obj:%s/%s}' % (self.page_keys[comp_page], self.obj_keys[comp_page][value])
        ref = self.ref(domain, value)
        return '${%s}' % ref if ref else None


def _identity_maps(page_count, pic_count, font_count, object_counts, page_names):
    ident = lambda n: {i: i for i in range(n)}
    return R.Maps(ident(page_count), ident(pic_count), ident(font_count), {i: ident(c) for i, c in enumerate(object_counts)},
                  dict(enumerate(page_names)), page_names, {i: {} for i in range(page_count)},
                  {i: set() for i in range(page_count)}, set())


def export_portable(source, destination):
    source, destination = Path(source), Path(destination)
    if P._lexists(destination):
        raise FileExistsError('Destination already exists: %s' % destination)
    files = H.read_container(source.read_bytes())
    if 'main.HMI' not in files:
        raise C.ConfigError('The project has no main.HMI')
    index = M.parse_index(files['main.HMI'])
    pairs = index.pairs()
    kinds = {k for k, _ in pairs}
    if kinds - {'pa', 'i', 'zi', 'gmov'}:
        raise C.ConfigError('Resource kinds %s cannot be exported to a portable project' % sorted(kinds - {'pa', 'i', 'zi', 'gmov'}))
    known = {n for _, n in pairs} | {n + 's' for k, n in pairs if k in ('i', 'gmov')} | {'main.HMI', 'Program.s'}
    extra = [n for n in files if n not in known]
    if extra:
        raise C.ConfigError('Files outside the project index cannot be exported to a portable project: %s' % ', '.join(extra[:5]))
    page_files = [n for k, n in pairs if k == 'pa']
    pages = [M.parse_page(files[n]) for n in page_files]
    used = set()

    def unique(raw, fallback):
        key, n = _slug(raw, fallback), 1
        base = key
        while key in used:
            n += 1
            key = '%s_%d' % (base, n)
        used.add(key)
        return key
    page_keys = [unique(p.name, f) for p, f in zip(pages, page_files)]
    used.clear()
    pic_files = [n for k, n in pairs if k == 'i']
    pic_keys = [unique('pic_' + n[:-2], n) for n in pic_files]
    used.clear()
    font_files = [n for k, n in pairs if k == 'zi']
    font_keys = [unique('font_' + n[:-3], n) for n in font_files]
    used.clear()
    anim_files = [n for k, n in pairs if k == 'gmov']
    anim_keys = [unique('anim_' + n[:-5], n) for n in anim_files]
    obj_keys = []
    for page in pages:
        used = set()
        keys = ['(page)']
        for i, o in enumerate(page.objects[1:], 1):
            name = o.get('objname').value.decode('utf8', 'replace') if o.get('objname') else 'obj%d' % i
            key, n = _slug(name, 'obj%d' % i), 1
            base = key
            while key in used or key == '(page)':
                n += 1
                key = '%s_%d' % (base, n)
            used.add(key)
            keys.append(key)
        obj_keys.append(keys)
    symbols = _Symbols(page_keys, pic_keys, font_keys, obj_keys, anim_keys)
    maps = _identity_maps(len(pages), len(pic_files), len(font_files), [len(p.objects) for p in pages], [p.name for p in pages])

    def code_line(raw, page_index):
        rw = R.Rewriter(maps, page_index, symbolize=symbols.placeholder)
        text = raw.decode('utf8', 'surrogateescape')
        return rw.run(text)

    def line_json(raw, page_index):
        try:
            raw.decode('utf8')
        except UnicodeDecodeError:
            return {'hex': raw.hex()}
        return code_line(raw, page_index)

    def attr_json(obj, code):
        out = {}
        for a in obj.attrs:
            if a.name in ('type', 'id'):
                continue
            value = M.decode_value(a.name, a.value)
            dom = R.attr_domain(code, a.name)
            if dom and isinstance(value, int):
                ref = symbols.ref(dom[0], value)
                if ref and value != dom[1]:
                    value = {'$ref': ref}
            out[a.name] = value
        # endx/endy are derived when they follow x/y/w/h
        for end, a_, b_ in (('endx', 'x', 'w'), ('endy', 'y', 'h')):
            if all(k in out for k in (end, a_, b_)) and all(isinstance(out[k], int) for k in (end, a_, b_)) \
                    and out[end] == out[a_] + out[b_] - 1:
                del out[end]
        return out

    # layouts: the most common layout per type; deviating objects carry their own
    layouts, counts = {}, {}
    for page in pages:
        for o in page.objects:
            counts.setdefault(o.get('type').value[0], {}).setdefault(json.dumps(_layout_of(o)), 0)
            counts[o.get('type').value[0]][json.dumps(_layout_of(o))] += 1
    for code, c in counts.items():
        layouts[str(code)] = json.loads(max(c, key=c.get))
    page_docs = []
    for pi, (page, key) in enumerate(zip(pages, page_keys)):
        for o in page.objects:
            seen = [a.name for a in o.attrs]
            if len(seen) != len(set(seen)):
                raise C.ConfigError('Page %s has a component with a repeated attribute; it cannot be exported' % page.name)

        def obj_json(o, root=False):
            code = o.get('type').value[0]
            d = {} if root else {'key': obj_keys[pi][page.objects.index(o)], 'type': H.TYPES.get(code, code)}
            skip = ('objname',) if root and o.get('objname') and o.get('objname').value.decode('utf8', 'replace') == page.name else ()
            attrs = attr_json(o, code)
            for k in skip:
                attrs.pop(k, None)
            d['attributes'] = attrs
            d['events'] = {e.label: [line_json(x, pi) for x in e.lines] for e in o.events}
            lay = _layout_of(o)
            if lay != layouts[str(code)]:
                d['layout'] = lay
            if o.extra:
                d['extra'] = o.extra
            if o.tail != b'\0\0\0\0':
                d['tail'] = o.tail.hex()
            return d
        hdr = bytes(page.header)
        doc = {'name': page.name, 'header': {'lock': hdr[16:24].hex(), 'writer': hdr[40:56].hex()},
               'root': obj_json(page.objects[0], True), 'objects': [obj_json(o) for o in page.objects[1:]]}
        page_docs.append((key, doc))
    program = files.get('Program.s')
    program_text = None
    if program is not None:
        text = program.decode('utf8', 'surrogateescape')
        out = []
        for line in text.splitlines(True):
            body = line.rstrip('\r\n')
            out.append(code_line(body.encode('utf8', 'surrogateescape'), None) + line[len(body):])
        program_text = ''.join(out).encode('utf8', 'surrogateescape')
    pngs = []
    for f, key in zip(pic_files, pic_keys):
        png = C._source_png(files.get(f + 's'))
        if png is None:
            raise C.ConfigError('Picture %s has no PNG source (%ss) and cannot be exported' % (f, f))
        pngs.append((key, png))
    anims = []
    for f, key in zip(anim_files, anim_keys):
        try:
            src = ANIM.validate_source(files.get(f + 's', b''))
            gm = ANIM._parse(files[f], 'gmov')
            ms = [fr['duration_ms'] for fr in gm['frames']]
            if len(ms) != len(src['pngs']) or ms != [fr['duration_ms'] for fr in src['frames']]:
                raise ValueError('source and compiled frames differ')
            entry = {'fps': gm['fps'], 'frames': [{'png': 'animations/%s/%03d.png' % (key, i), 'ms': m}
                                                  for i, m in enumerate(ms)]}
            if gm['opaque']:
                entry['opaque'] = True
            anims.append((key, entry, src['pngs']))
        except ValueError:
            entry = {'gmov': 'animations/%s.gmov' % key}
            if f + 's' in files:
                entry['gmovs'] = 'animations/%s.gmovs' % key
            anims.append((key, entry, None))
    order = []
    for k, _ in pairs:
        if k not in order:
            order.append(k)
    config = {'format': C.FORMAT, 'portable': True,
              'project': {'header': bytes(index.header).hex(), 'index_order': order},
              'layouts': layouts,
              'pages': [{'key': k, 'content': {'mode': 'json', 'path': 'pages/%s.json' % k}} for k in page_keys],
              'pictures': [{'key': k, 'source': {'png': 'pictures/%s.png' % k}} for k in pic_keys],
              'fonts': [{'key': k, 'source': {'zi': 'fonts/%s.zi' % k}} for k in font_keys],
              'animations': [dict(key=k, **entry) for k, entry, _ in anims]}
    if program_text is not None:
        config['program'] = 'Program.s'
    destination.mkdir(parents=True)
    try:
        for sub in ('pages', 'pictures', 'fonts', 'animations'):
            (destination / sub).mkdir(parents=True)
        for key, doc in page_docs:
            (destination / 'pages' / (key + '.json')).write_bytes(P.json_bytes(doc))
        for key, png in pngs:
            (destination / 'pictures' / (key + '.png')).write_bytes(png)
        for f, key in zip(font_files, font_keys):
            (destination / 'fonts' / (key + '.zi')).write_bytes(files[f])
        for f, (key, entry, frames) in zip(anim_files, anims):
            if frames is not None:
                (destination / 'animations' / key).mkdir()
                for fr, png in zip(entry['frames'], frames):
                    (destination / fr['png']).write_bytes(png)
            else:
                (destination / entry['gmov']).write_bytes(files[f])
                if 'gmovs' in entry:
                    (destination / entry['gmovs']).write_bytes(files[f + 's'])
        if program_text is not None:
            (destination / 'Program.s').write_bytes(program_text)
        (destination / 'project.json').write_bytes(P.json_bytes(config))
    except BaseException:
        shutil.rmtree(destination, ignore_errors=True)
        raise
    return {'directory': str(destination), 'pages': len(pages), 'pictures': len(pic_files), 'fonts': len(font_files),
            'animations': len(anim_files)}


# ------------------------------------------------------------------ build

class PortableCompiler:
    def __init__(self, root, cfg):
        self.root, self.cfg = Path(root).resolve(), cfg
        C._dict(cfg, ('format', 'portable', 'project', 'layouts', 'pages', 'pictures', 'fonts', 'animations', 'program',
                      'acknowledge'), 'config', ('format', 'portable', 'project', 'pages', 'pictures', 'fonts'))
        proj = C._dict(cfg['project'], ('header', 'index_order'), 'project', ('header',))
        try:
            self.header = bytes.fromhex(proj['header'])
        except (ValueError, TypeError) as e:
            raise C.ConfigError('project.header must be hex') from e
        if len(self.header) != M.INDEX_HEADER_SIZE:
            raise C.ConfigError('project.header must have %d bytes' % M.INDEX_HEADER_SIZE)
        self.order = C._list(proj.get('index_order', ['i', 'zi', 'gmov', 'pa']), 'project.index_order')
        self.layouts = C._map(cfg.get('layouts', {}), 'layouts')
        self.findings = []
        self.page_specs = self._pages()
        self.pics = self._entries('pictures', ('key', 'source'), 'picture')
        self.fonts = self._entries('fonts', ('key', 'source'), 'font')
        self.anims = self._entries('animations', ('key', 'gmov', 'gmovs', 'frames', 'fps', 'opaque'), 'animation', source=False)
        self.page_ids = {p['key']: i for i, p in enumerate(self.page_specs)}
        self.pic_ids = {e['key']: i for i, e in enumerate(self.pics)}
        self.font_ids = {e['key']: i for i, e in enumerate(self.fonts)}
        self.anim_ids = {e['key']: i for i, e in enumerate(self.anims)}
        self.obj_ids = {p['key']: {o['key']: n for n, o in enumerate(p['objects'], 1)} for p in self.page_specs}
        if not 1 <= len(self.page_specs) <= 255:
            raise C.ConfigError('A project needs 1..255 pages')
        if len(self.pics) > 65535 or len(self.fonts) > 256:
            raise C.ConfigError('Too many pictures (max 65535) or fonts (max 256)')
        self.maps = _identity_maps(len(self.page_specs), len(self.pics), len(self.font_ids),
                                   [len(p['objects']) + 1 for p in self.page_specs], [p['name'] for p in self.page_specs])
        self.page_size = None

    # -- specs
    def _read(self, rel, label):
        return P._safe_workspace_path(self.root, rel, label + ' ' + str(rel)).read_bytes()

    def _entries(self, section, allowed, label, source=True):
        out, keys = [], set()
        for n, e in enumerate(C._list(self.cfg[section] if section in self.cfg else [], section)):
            where = '%s[%d]' % (section, n)
            C._dict(e, allowed, where, ('key',))
            key = C._key(e['key'], where + '.key')
            if key in keys:
                raise C.ConfigError('Duplicate %s key %r' % (label, key))
            keys.add(key)
            out.append(dict(e, where=where))
        return out

    def _pages(self):
        specs, keys = [], set()
        for n, entry in enumerate(C._list(self.cfg['pages'], 'pages')):
            where = 'pages[%d]' % n
            C._dict(entry, ('key', 'content'), where, ('key', 'content'))
            key = C._key(entry['key'], where + '.key')
            if key in keys:
                raise C.ConfigError('Duplicate page key %r' % key)
            keys.add(key)
            c = C._dict(entry['content'], ('mode', 'path', 'name', 'header', 'root', 'objects'), where + '.content', ('mode',))
            if c['mode'] == 'json':
                doc = C.load_json(P._safe_workspace_path(self.root, c.get('path', ''), 'Page content'), str(c.get('path')))
            elif c['mode'] == 'inline':
                doc = {k: c[k] for k in c if k != 'mode'}
            else:
                raise C.ConfigError('%s: portable pages use content mode json or inline' % where)
            C._dict(doc, ('name', 'header', 'root', 'objects'), where + ' content', ('name',))
            name = doc['name']
            if not isinstance(name, str) or not name or len(name.encode('utf8')) > 16 or '\0' in name:
                raise C.ConfigError('%s: invalid page name %r' % (where, name))
            if name in {s['name'] for s in specs}:
                raise C.ConfigError('%s: duplicate page name %r' % (where, name))
            objects, okeys = [], set()
            for m, o in enumerate(C._list(doc.get('objects', []), where + '.objects')):
                w = '%s.objects[%d]' % (where, m)
                C._dict(o, ('key', 'type', 'attributes', 'events', 'layout', 'extra', 'tail'), w, ('key', 'type'))
                k = C._key(o['key'], w + '.key')
                if k in okeys or k == '(page)':
                    raise C.ConfigError('%s: duplicate object key %r' % (w, k))
                okeys.add(k)
                C._map(o.get('attributes', {}), w + '.attributes')
                C._map(o.get('events', {}), w + '.events')
                objects.append(dict(o, where=w))
            if len(objects) + 1 > M.MAX_OBJECTS:
                raise C.ConfigError('%s: a page holds at most %d components besides the page object' % (where, M.MAX_OBJECTS - 1))
            root = C._dict(doc.get('root', {}), ('attributes', 'events', 'layout', 'extra', 'tail'), where + '.root')
            specs.append({'key': key, 'name': name, 'header': doc.get('header', {}), 'root': root, 'objects': objects,
                          'where': where})
        return specs

    # -- placeholders
    def resolve(self, kind, key):
        try:
            if kind == 'page':
                return self.page_ids[key]
            if kind == 'pagename':
                return self.page_specs[self.page_ids[key]]['name']
            if kind == 'picture':
                return self.pic_ids[key]
            if kind == 'font':
                return self.font_ids[key]
            if kind == 'animation':
                return self.anim_ids[key]
            pk, _, ok = key.partition('/')
            if kind == 'obj':
                return 0 if ok in ('', '(page)') else self.obj_ids[pk][ok]
            if kind == 'objname':
                ps = self.page_specs[self.page_ids[pk]]
                if ok in ('', '(page)'):
                    return ps['name']
                return C._name_text(ps['objects'][self.obj_ids[pk][ok] - 1]['attributes'].get('objname'))
        except KeyError as e:
            raise C.ConfigError('Unknown reference ${%s:%s}' % (kind, key)) from e
        raise C.ConfigError('Unknown reference kind ${%s:%s}' % (kind, key))

    def _line(self, raw, site, page_index=None):
        text = raw.decode('utf8', 'surrogateescape')
        rw = R.Rewriter(self.maps, page_index, forbid=True)
        rw.run(text)
        for f in rw.findings:
            if f.kind == 'newref':
                self.findings.append('%s: %s\n    %s' % (site, f.message, text.strip()))
        return R.expand(text, self.resolve).encode('utf8', 'surrogateescape')

    # -- objects
    def _ref(self, value, domain, where):
        label = {'pic': 'picture', 'anim': 'animation'}.get(domain, domain)
        table = {'page': self.page_ids, 'pic': self.pic_ids, 'font': self.font_ids, 'anim': self.anim_ids}[domain]
        kind, _, key = str(value['$ref']).partition(':')
        if kind != label:
            raise C.ConfigError('%s: this attribute takes a %s reference, not %r' % (where, label, value['$ref']))
        if key not in table:
            raise C.ConfigError('%s: unknown %s key %r' % (where, label, key))
        return table[key]

    def build_object(self, spec, code, object_id, where, root=False):
        layout = spec.get('layout') or self.layouts.get(str(code))
        creatable = code in F.CREATABLE
        if layout is None:
            if not creatable:
                raise C.ConfigError('%s: no layout is known for type %d' % (where, code))
            layout = [[n, w if w else TEXT] for n, w, _d, _a in F.profile(code)[0]]
        defaults = {}
        if creatable:
            defaults = {n: d for n, _w, d, _a in F.profile(code)[0] if d is not None}
        values = dict(spec.get('attributes', {}))
        names = [n for n, _ in layout]
        for k in values:
            if k not in names:
                raise C.ConfigError('%s: unknown attribute %r for this component' % (where, k))
        attrs = []
        for name, width in layout:
            if name == 'type':
                raw = bytes((code,)) if width == 1 else M.encode_value(name, code, width)
            elif name == 'id':
                raw = M.encode_value(name, object_id, width)
            elif name in values:
                value = values[name]
                dom = R.attr_domain(code, name)
                if isinstance(value, dict) and set(value) == {'$ref'}:
                    if not dom:
                        raise C.ConfigError('%s.%s is not a reference attribute' % (where, name))
                    value = self._ref(value, dom[0], '%s.%s' % (where, name))
                elif dom and isinstance(value, int) and not isinstance(value, bool) and value != dom[1] \
                        and 0 <= value < {'pic': len(self.pics), 'font': len(self.fonts), 'page': len(self.page_specs),
                                          'anim': len(self.anims)}[dom[0]]:
                    raise C.ConfigError('%s.%s: write {"$ref": "%s:key"} instead of the number %d' % (
                        where, name, {'pic': 'picture', 'anim': 'animation'}.get(dom[0], dom[0]), value))
                raw = M.encode_value(name, value, width if width in (1, 2, 4) else None)
            elif name in ('endx', 'endy') and all(k in values for k in (('x', 'w') if name == 'endx' else ('y', 'h'))):
                a_, b_ = ('x', 'w') if name == 'endx' else ('y', 'h')
                raw = M.encode_value(name, values[a_] + values[b_] - 1, width)
            elif name in defaults:
                raw = defaults[name]
            elif root and name == 'objname':
                raw = None
            else:
                raise C.ConfigError('%s: attribute %r is missing' % (where, name))
            attrs.append(M.Attr(name, raw if raw is not None else b''))
        events = []
        for label, lines in spec.get('events', {}).items():
            if not label.startswith('codes'):
                raise C.ConfigError('%s: event names start with "codes" (got %r)' % (where, label))
            events.append(M.Event(label, [self._line(x, '%s/%s#%d' % (where, label, i + 1)) for i, x in
                                          enumerate(C._event_lines(lines, '%s.events.%s' % (where, label)))]))
        if creatable and not events:
            events = [M.Event(l, []) for l in F.profile(code)[1]]
        try:
            tail = bytes.fromhex(spec['tail']) if 'tail' in spec else b'\0\0\0\0'
        except (ValueError, TypeError) as e:
            raise C.ConfigError('%s: tail must be hex' % where) from e
        extra = spec.get('extra', 0)
        if isinstance(extra, bool) or not isinstance(extra, int) or not 0 <= extra < 1 << 32:
            raise C.ConfigError('%s: extra must be a u32' % where)
        return M.Obj(attrs, events, tail, extra)

    def build_page(self, ps):
        where = ps['where']
        hdr = bytearray(M.PAGE_HEADER_SIZE)
        h = C._map(ps['header'], where + '.header')
        try:
            hdr[16:24] = bytes.fromhex(h.get('lock', '00' * 8)).ljust(8, b'\0')[:8]
            hdr[40:56] = bytes.fromhex(h.get('writer', '00' * 16)).ljust(16, b'\0')[:16]
        except (ValueError, TypeError) as e:
            raise C.ConfigError('%s.header must be hex' % where) from e
        root_spec = dict(ps['root'])
        attrs = dict(root_spec.get('attributes', {}))
        attrs.setdefault('objname', ps['name'])
        root_spec['attributes'] = attrs
        if self.page_size and not any(k in attrs for k in ('w', 'h')):
            attrs.update(w=self.page_size[0], h=self.page_size[1])
        attrs.setdefault('x', 0)
        attrs.setdefault('y', 0)
        root = self.build_object(root_spec, 121, 0, where + '.root', root=True)
        objs = [root]
        for n, so in enumerate(ps['objects'], 1):
            w = '%s.objects[%d](%s)' % (where, n - 1, so['key'])
            objs.append(self.build_object(so, C._type_any(so['type'], w), n, w))
        names = set()
        for o in objs[1:]:
            nm = o.get('objname').value.decode('utf8', 'replace') if o.get('objname') else None
            if nm in names:
                raise C.ConfigError('%s: duplicate component name %r' % (where, nm))
            names.add(nm)
        page = M.Page(bytes(hdr), objs)
        try:
            page.name = ps['name']
        except M.ModelError as e:
            raise C.ConfigError('%s: %s' % (where, e)) from e
        return page

    # -- all
    def compile(self):
        for ps in self.page_specs:        # page size for new pages: the first page that states one
            w, h = ps['root'].get('attributes', {}).get('w'), ps['root'].get('attributes', {}).get('h')
            if isinstance(w, int) and isinstance(h, int):
                self.page_size = (w, h)
                break
        files, final = {}, {'i': [], 'zi': [], 'gmov': [], 'pa': []}
        counters = {'i': 0, 'zi': 0, 'gmov': 0, 'pa': 0}

        def name(kind, ext):
            n = counters[kind]
            counters[kind] += 1
            final[kind].append('%d.%s' % (n, ext))
            return '%d.%s' % (n, ext)
        for e in self.pics:
            src = C._dict(e.get('source', {}), ('png',), e['where'] + '.source', ('png',))
            try:
                compiled, source = IMG.encode_png(self._read(src['png'], 'Picture source'))
            except ValueError as exc:
                raise C.ConfigError('%s: %s' % (e['where'], exc)) from exc
            n = name('i', 'i')
            files[n], files[n + 's'] = compiled, source
        for e in self.fonts:
            src = C._dict(e.get('source', {}), ('zi', 'ttf', 'height', 'chars', 'chars_file', 'layout', 'bpp', 'name', 'size',
                                                'font_index'), e['where'] + '.source')
            if 'zi' in src:
                data = self._read(src['zi'], 'Font')
            elif 'ttf' in src:
                from hmi_font import encode_ttf
                chars = src.get('chars')
                if 'chars_file' in src:
                    chars = P._parse_chars_file(P._safe_workspace_path(self.root, src['chars_file'], 'Character file'))
                try:
                    data = encode_ttf(str(P._safe_workspace_path(self.root, src['ttf'], 'Font source')), height=src.get('height'),
                                      chars=chars, name=src.get('name'), bpp=src.get('bpp'), size=src.get('size'),
                                      font_index=src.get('font_index', 0), layout=src.get('layout'))
                except ValueError as exc:
                    raise C.ConfigError('%s: %s' % (e['where'], exc)) from exc
            else:
                raise C.ConfigError('%s needs source.zi or source.ttf' % e['where'])
            files[name('zi', 'zi')] = data
        for e in self.anims:
            if 'frames' in e:
                if 'gmov' in e or 'gmovs' in e:
                    raise C.ConfigError('%s: use either frames or gmov/gmovs' % e['where'])
                if not isinstance(e.get('opaque', False), bool):
                    raise C.ConfigError('%s.opaque must be true or false' % e['where'])
                frames = C._list(e['frames'], e['where'] + '.frames')
                pngs, ms = [], []
                for k, fr in enumerate(frames):
                    C._dict(fr, ('png', 'ms'), '%s.frames[%d]' % (e['where'], k), ('png', 'ms'))
                    pngs.append(self._read(fr['png'], 'Animation frame'))
                    ms.append(fr['ms'])
                try:
                    gmov, gmovs = ANIM.encode_animation(pngs, ms, e.get('fps', 10), opaque=e.get('opaque', False) is True)
                except ValueError as exc:
                    raise C.ConfigError('%s: %s' % (e['where'], exc)) from exc
                n = name('gmov', 'gmov')
                files[n], files[n + 's'] = gmov, gmovs
                continue
            if 'gmov' not in e:
                raise C.ConfigError('%s needs "frames" or "gmov"' % e['where'])
            n = name('gmov', 'gmov')
            files[n] = self._read(e['gmov'], 'Animation')
            if 'gmovs' in e:
                files[n + 's'] = self._read(e['gmovs'], 'Animation source')
        for ps in self.page_specs:
            data = bytearray(self.build_page(ps).to_bytes())
            if data[21] == I.FILE_ID and data[22] == I.FORMAT_VERSION:     # keep the writer version of an exported page
                struct.pack_into('<I', data, 0, I.page_checksum(data))
            files[name('pa', 'pa')] = bytes(data)
        program = self.cfg.get('program')
        if program is not None:
            text = self._read(program, 'Program').decode('utf8', 'surrogateescape')
            out = []
            for n, line in enumerate(text.splitlines(True), 1):
                body = line.rstrip('\r\n')
                out.append(self._line(body.encode('utf8', 'surrogateescape'), 'Program.s#%d' % n).decode('utf8', 'surrogateescape')
                           + line[len(body):])
            files['Program.s'] = ''.join(out).encode('utf8', 'surrogateescape')
        if self.findings:
            raise C.ConfigError('Reference problems:\n  ' + '\n  '.join(self.findings[:20]))
        order = [k for k in self.order if k in final] + [k for k in final if k not in self.order]
        records = [(k, n) for k in order for n in final[k]]
        index = M.Index(self.header, [], b'')
        try:
            index.records = [M.Index.make_record(k, n) for k, n in records]
            files['main.HMI'] = index.to_bytes()
        except M.ModelError as e:
            raise C.ConfigError(str(e)) from e
        out_files = {}
        for kind in ('i', 'zi', 'gmov', 'pa'):
            for n in final[kind]:
                out_files[n] = files[n]
                if n + 's' in files:
                    out_files[n + 's'] = files[n + 's']
        for n in ('Program.s', 'main.HMI'):
            if n in files:
                out_files[n] = files[n]
        if len(out_files) > M.MAX_RECORDS:
            raise C.ConfigError('The project would exceed %d files' % M.MAX_RECORDS)
        return C.Candidate(out_files, set(out_files), {
            'portable': True, 'pages': len(self.page_specs), 'pictures': len(self.pics), 'fonts': len(self.fonts),
            'animations': len(self.anims), 'files': len(out_files)})


def compile_portable(directory, cfg):
    try:
        return PortableCompiler(directory, cfg).compile()
    except C.ConfigError:
        raise
    except (M.ModelError, ValueError) as e:
        raise C.ConfigError(str(e)) from e
    except (TypeError, AttributeError, KeyError, IndexError) as e:
        raise C.ConfigError('Malformed config (%s: %s)' % (type(e).__name__, e)) from e
